name: CI-ZaharenkoSerhii_З-21  # Название workflow

on:  # Условия запуска
  push:  # При пуше в ветки:
    branches: [ main, boba ]  # main, master или dev (если нет dev — создайте её)

jobs:
  build:
    name: CMake build  # Название задачи
    runs-on: ubuntu-latest  # ОС для сборки

    steps:
      # 1. Клонирование репозитория
      - name: Clone repository
        uses: actions/checkout@v4

      # 2. Конфигурация CMake
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      # 3. Сборка проекта
      - name: Build project
        run: |
          cd build
          cmake --build .

      # 4. Запуск программы
      - name: Run program
        run: |
          cd build
          ./TTC